---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tandoor-secrets
  namespace: tandoor
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA/8q8mi/wibYF6FJjiXtvsWC7HTDVL0llkcHXFO+//YafMZNDIpnPDXwNg2vExua/nzKM+YP8mAb0FQV5T9920Ou02+Rnr2zBnW+QXgyalN+nyzXwKLMAb9iRbqkLyNvM3fqtRJXgVPwCIm5Sg3QE0dkFUD1/XsFtp+ArAY1iFLhE4Jq6GLD0ItwzSBIcAD7HuJhJpiN9fzQY7/ybYiFrsRuPmYY6xk/aQY5FrfFCGUP4Nw9ibtDzj613aX4o9o7kZcO1jk8jK74Zzgy7cpDZ0pHERh1d10QdTlYI30MKl6tran06t8vTiYRnT0w/+DnHLdHtdEVeGJvdf+HrvR4gw1ywWNsaRR8gIJq2LbLI8PjW620mCj8eVT1QV9ybfGXxOwXQOabdvsM35nIn0yx4MOc0aHLjWQG3HgYIKF/TtDDqblzz1S4thIeY/e4qkFUmOUQf6+ks5YH5baFzsQ6hZWsGfsxMz6jgRk/QKr/qoR0AMxZqJU8mX2+ZmF001MzcEkQBi2/OkN4dILQnyuU7UsNf6KPaskdF2q2phoiljJMqF/v6VrNoRYwOPlSyrrbmvV9AUBd3KjprGiX/dSK3Ibmtw9PFjhfa8mArAqgc77gNNqePgG/agUIgsfqYxI2wTFSgXXAQFziKBoCVgJRfF9akkeyox86dBS+sUYFPJmwkwLpAYH6BlVTx5vonnsSxy9Vp0qK4SQlOM47G+jutRhkbtSAjULZlySsw=
    SECRET_KEY: AgAEfrERstRx1taSe2khVDFKmjsUpEpxAJjEGP04ESJxq5F0w8GlpweQ8eLkyAcHfbSEoB0B4GBl8twbw5xPF81OSFk+GocF05P7pnz4BpeB5/em97EAADTQjZ0g2ivVoRzcK/MBIAelHyx4hLt0PF525/mBXygHqepDWvQxHv/BFK2VCOJPmuBobqzXgzcx+/VWAExaD1Fe9Sc0CE+jz2Ng+cSY4YSr5oAFm5XqUaIhMs9dXeCgKMH4OakE4z1cOWbPFsEaON3GwXbdtZ81uoS8M3ZPn8v6MLcwLjWnpBPFYjeIoj91pvSSSUeUJw8vYLZEZoQsru3nC08IsAzTmNzogWDdGnFaAfydJKKqSahYgPtQD4VCAERe6kU76emg71+pXoUZj/ifpB+6RU2CMpjIB32AZbEUVrjH0+tRdvMZWTcoWl53hqMdrOnCi/XRc4ix3RB8DRNpC4ZBvcCntarq7FjUrcraLa2N5kCmrfdmarf2B0zK3r46xxhuAdfGIpsq7c/79whRunRk9qJKN7R9a2wI1rmm8cmtKjSia/d48jGXho0qDId2ugK3dunxU6Q3Yrjabq/Cdtnaglul9VSsoNzCrIR8BMoUGYRfIY2jk+FRnyB3dprUYSoixH77Lkf73VcPTDr/rrJN8I5JOXGsv7bGn2u0KfZE7R/EZjaSEbTowslPo4To50NVhHeTd/IUVFyrVYuA/Kqgr+one6iWBN+ErXJI0j/rAPxuI6V7LxrG
  template:
    metadata:
      name: tandoor-secrets
      namespace: tandoor
    type: Opaque
