#!/usr/bin/env python3
"""Snapshot Ingress routes and running container images from the cluster,
render them as HTML, and push that HTML onto a BookStack page.

Requires: pip install kubernetes requests

Reads the kubeconfig your `kubectl` already uses (~/.kube/config or
$KUBECONFIG) by default, falling back to in-cluster config if that's not
available - so this also works unmodified if it's ever run as a CronJob
inside the cluster instead of by hand.

Required environment variables:
  BOOKSTACK_URL            e.g. https://wiki.matt-host.de
  BOOKSTACK_TOKEN_ID       BookStack API token ID (Settings > API Tokens)
  BOOKSTACK_TOKEN_SECRET   BookStack API token secret
  PAGE_ID                  numeric ID of the BookStack page to overwrite

Usage:
  BOOKSTACK_URL=https://wiki.matt-host.de \\
  BOOKSTACK_TOKEN_ID=... BOOKSTACK_TOKEN_SECRET=... PAGE_ID=5 \\
    python3 scripts/auto-doc-cluster.py
"""

import html
import os
import sys
from datetime import datetime, timezone

import requests
from kubernetes import client, config

NAMESPACES = ["argocd", "tandoor", "tandoor-staging", "immich", "monitoring", "bookstack", "longhorn-system"]
REQUIRED_ENV_VARS = ["BOOKSTACK_URL", "BOOKSTACK_TOKEN_ID", "BOOKSTACK_TOKEN_SECRET", "PAGE_ID"]


def load_k8s_config():
    try:
        config.load_kube_config()
    except config.ConfigException:
        config.load_incluster_config()


def collect_ingress_routes(networking_api, namespaces):
    rows = []
    for ns in namespaces:
        for ing in networking_api.list_namespaced_ingress(ns).items:
            for rule in ing.spec.rules or []:
                host = rule.host or "*"
                paths = rule.http.paths if rule.http else []
                for path in paths:
                    svc = path.backend.service if path.backend else None
                    if svc and svc.port and svc.port.number:
                        port = str(svc.port.number)
                    elif svc and svc.port and svc.port.name:
                        port = svc.port.name
                    else:
                        port = "-"
                    rows.append(
                        {
                            "namespace": ns,
                            "ingress": ing.metadata.name,
                            "host": host,
                            "path": path.path or "/",
                            "service": svc.name if svc else "-",
                            "port": port,
                        }
                    )
    return rows


def collect_container_images(core_api, namespaces):
    rows = []
    for ns in namespaces:
        for pod in core_api.list_namespaced_pod(ns).items:
            if pod.status.phase != "Running":
                continue
            for container in pod.spec.containers or []:
                rows.append(
                    {
                        "namespace": ns,
                        "pod": pod.metadata.name,
                        "container": container.name,
                        "image": container.image,
                    }
                )
    return rows


def render_table(headers, rows, keys):
    head_html = "".join(f"<th>{html.escape(h)}</th>" for h in headers)
    body_html = "".join(
        "<tr>" + "".join(f"<td>{html.escape(str(row[k]))}</td>" for k in keys) + "</tr>"
        for row in rows
    )
    return (
        '<table border="1" cellpadding="6" cellspacing="0">'
        f"<thead><tr>{head_html}</tr></thead><tbody>{body_html}</tbody></table>"
    )


def render_html(ingress_rows, image_rows):
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    ingress_table = render_table(
        ["Namespace", "Ingress", "Host", "Path", "Service", "Port"],
        ingress_rows,
        ["namespace", "ingress", "host", "path", "service", "port"],
    )
    image_table = render_table(
        ["Namespace", "Pod", "Container", "Image"],
        image_rows,
        ["namespace", "pod", "container", "image"],
    )

    return (
        f"<p><em>Auto-generated by scripts/auto-doc-cluster.py - last updated {generated_at}.</em></p>"
        "<h2>Ingress Routes</h2>"
        f"{ingress_table}"
        "<h2>Running Container Images</h2>"
        f"{image_table}"
    )


def update_bookstack_page(page_html):
    base_url = os.environ["BOOKSTACK_URL"].rstrip("/")
    page_id = os.environ["PAGE_ID"]

    response = requests.put(
        f"{base_url}/api/pages/{page_id}",
        headers={
            "Authorization": f"Token {os.environ['BOOKSTACK_TOKEN_ID']}:{os.environ['BOOKSTACK_TOKEN_SECRET']}",
            "Content-Type": "application/json",
        },
        json={"html": page_html},
        timeout=30,
    )
    response.raise_for_status()


def main():
    missing = [name for name in REQUIRED_ENV_VARS if not os.environ.get(name)]
    if missing:
        sys.exit(f"Missing required environment variables: {', '.join(missing)}")

    load_k8s_config()
    core_api = client.CoreV1Api()
    networking_api = client.NetworkingV1Api()

    ingress_rows = collect_ingress_routes(networking_api, NAMESPACES)
    image_rows = collect_container_images(core_api, NAMESPACES)
    update_bookstack_page(render_html(ingress_rows, image_rows))

    print(
        f"Updated BookStack page {os.environ['PAGE_ID']} with "
        f"{len(ingress_rows)} ingress routes and {len(image_rows)} container "
        f"images across {', '.join(NAMESPACES)}."
    )


if __name__ == "__main__":
    main()
