[docker_servers]
oracle-main ansible_host=[IP] ansible_user=[USER] ansible_ssh_private_key_file=~/.ssh/KEYPATH.key

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'