---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ntfy-alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    config: AgCSPRoLdBLg9sKgirbzgRfLzReWEXfiPZUO6mEweuij6/jLTKJA8BDuyLBZYN4d0VWxTOJiYbNFlhgnYBr+NhL6XTclFd3uFkeHic9vKACHeqg4OsutOEBmcV+PEGMdXbIW+nCe6XiSkn7DD+4ZH2E+XF20J6aYpaA+XoWBt+oCYsZhpOfqnVF8kDnlACIUDHf7dKYyq2ck64kFZXCTFDaceZUaxukn91YCVtNK9YCKwGWB2rUxqQ8cPDhDaflqOn8id2wL0WhAzMautBgybK6Iqtx9ZMMQltUVj2fMV9HH0sycSKlB0c8Jxw4FeI2GJF4OoYW2gzdftaCpcjk5dl1Q/UGxqpxDmM5Umr7gyI1oXh/X2rAW3nDSX3DuFta7xQ8CTZKf4NaPLsDSvODNHUYPFz85ymdBjMqAa8d0/CcPL+wvJitZ+B7UdOmFtOnSpZ3P0Yl1iiSsBZCFzlv9e6zRq7/U36ZmgnFSewTcewFs83sOyGv1wt/6c4v6833zdrQHihwItdLBEmJr5d8bno7y/qu3gtNUg5CR0Eb+ChLTXbLU6Kp1V9dYHv83tU3JiNsraZ96PEl+2FoASr7FscKP2NZbPYD8eFbnaK8LdsuIatv4r369f2vpypxWdSAcWKm5hxmn8qG1OAuSWmX4YNKpGrTU5q+9Z2Nk+SVKKdeUBmozetirx7cAYRnJWAQkjbYp8pPaUw6OrYzjIieaEbRI7Bd2Epk/gvBaVvqLT5xuIeoFyi6VKX3tjYoRPQRmUjZkyOS9yGm/0SUmNVXl6Cka6Gapen7IWfBhi90ozrh8HLIBdkc7MvSsd4HwyYc4MyVLXCaRnm1Wm3aGmD2dC5+hbUWCLCZBMRrEASBjIBJ72y4hWAktAYIf1otSuUdOU/eukztIEwrVo760BsP3yPpte42Es9DN3sfwiUocM5ldR1ipyWx68M1mIHSyIcpb45jjWsbCp+aAZVqqvLRuCWsDWnJTBK0VUyIhAsSulH1fowtOxLwlJiF2SJ1jgHFICkhAJvJJ0+9/Gy7AvFqNkTguDefuCZOSlxOkPZr51lYnRZhfBU15TJOSufm5a5V2PbhHI4UdGVqIQPTS/q968rfFGOfI/X2YtOKySwp4iPogR6Iwdy2jciqs3So5l9bqUqyiNkDJ6+pKeL2afxVbgoYvDQbSXDYVGQtpj5QXAybCuyoRH5cu2sa0gubW6vrPAIploVAa7gHOFvCxE4b5iHr2Hg13aVJUVLVo7ALApeREUsWSDLd8IEwUKHEziFTf8/akpmBfpuB0mjNHjUP09fnE+jeliaZwi+Sj7eewTHpRMHJOBrbvnV3GyzgJojEwf8obwUxVajPvT0ZHvjOZlQbalBrP
  template:
    metadata:
      name: ntfy-alertmanager-config
      namespace: monitoring
