---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ntfy-alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    config: AgAC2sbRUfKGl5B7F/Ru/wMyCUwjBQNcRva/H1BTdQ0TTwF3LXXtiFvf1tRCIU++i7D4W2uXYhURqN7joNjGwHO11+npUVPEFelDhapRfSmpogjYpyzj+vp/1G2G2Pz+5G7VBHXDM+ZSaovfmsfgx8Id5MlnJhb6W3aL6CGL16a61s7zJ/Ts43mB7wZa235HsVdiLOSNc8jDpvNJqYgCYhdpIhxs9sXVMVr/P9FX6xI83Q+8K3gKBThZFo/846syUkITBzvnCu3XhbGWeRIiA5uQ8gUFe2doilw7ncvQ68WOqgtLrb89oimZtduLd/RE19Rr9WEpu0SNro+7dlZoCOH+YDw1uo6LyVQGeme0g7YVHWJVWGdhazD7M3VPneCKiFRThbpcwBr5xJ+pGkfK3dkSjM0O/4d/qGqksQX+btSqvMXTWNbQ2XgBHdqLAhwwLX1RHgslNgyhpTXZz3j/ciuIyFpdE0p+etAUEfC41FDJ/6IFK/JEsCHLt4mAifvqPCaGHlR9iU9mk4d63fjjUWlzu9MlbXsdF9AtY1wleHKLaHPGrTDZracq1EwQVWAvVrJIWauDMZlX2EsEwn8AWuhKDQxpWlq/X149MxB7vwn2l07qK75gD5LPxCaUytnaaFlEQKv3NtsNA9GfZeBzZN9orUWL9muH/aI9MYihMd2F7Z7hcJOaPM6EduyTHV9zYkjiFzVE04YzlFR7HTNwjItGPOr8WMOgzik0kqfpJQn/lS1QLHWnh92H99nphOGErU1V7yguCMjzlS9t1fgP5v+hFzFsBjjDN/854Q3FImiOdAZBdLiDEsiIsFIdn9Rcpwm7pFkTxcy5rHaFxlkfCFe/NoFpFN3Gym0KJOlat9kBOQEE30ItoLq/soGgGfAXZWIL5z29fZ6AyqC+u1zbcIz/0Sxd7YFNtGhiTA6sjaJOO3Vmi6KxK84DYFFUZ0iodFRgHG/Jij3QX/Xzy/+jFHBJSOXsael39LHOYS+O/yUSWOvdhR9D2+aMTpPpQRS8GJqgvioatAwYB1XUKLxcmlz4NjEFvAIyMoYpaKv3sHV3VS95qs85ch8HQ6GgKyKB+BCqTAQh2OCKeIFhXIQoVrQZWJ7++ggovNDKQOTGk/dChWLRLQgVw5qMPhZHkX+QIc9bkylqqpTGHQEIaEoUnehtYvfbK5ad3gnKlrXNMALx0fJHuMDyytj2CqgZoGg5XFyO3sN9XA0/UycJ6W712lWruibxunt6LRbLoy8K09MIPOAYOnjE46NhMquM2lD+qOKXXXm5JQSpSIBE1FPWo3VMg0/tLViAKDOvraRHGIw4e+dVG9aRkNJLT6+ux9wuB3QjKcTOM4R3rV/8Sbh7r0U=
  template:
    metadata:
      name: ntfy-alertmanager-config
      namespace: monitoring
